spring:
  application:
    name: springbatchdemo
  datasource:
    hikari:
      jdbc-url: jdbc:h2:file:~/test
      driver-class-name: org.h2.Driver
      username: sa
      password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  liquibase:
    enabled: true
